import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
process.env.ARC_MCP_LABEL = 'live-check';
const { HANDLERS: H } = await import('../src/registry.js');
const { createAxDriver } = await import('../src/ax.js');
const ax = createAxDriver();
const guard = () => { try { execSync('/private/tmp/claude-501/-Users-db-Burnes-Center-Fulltime-ME/2d0e1ee7-52d8-489a-b564-da766d0888ce/scratchpad/arcprobe/guard.sh', { stdio: 'pipe' }); } catch (e) { console.log(String(e.stdout)); process.exit(3); } };
const frames = async () => JSON.stringify((await ax.frames()).map((f) => [f.id.slice(0, 4), f.x, f.y, f.width, f.height]));
const shown = (r) => JSON.stringify(r, (k, v) => (k === 'url' || k === 'title' || k === 'data') ? undefined : v).slice(0, 420);
const ds = async (tab) => (await H.execute_javascript({ tab_id: tab, code: 'JSON.stringify(document.body.dataset)' })).result;
console.log('frames before', await frames());
guard(); const o = await H.open_url({ url: 'file:///private/tmp/claude-501/-Users-db-Burnes-Center-Fulltime-ME/2d0e1ee7-52d8-489a-b564-da766d0888ce/scratchpad/arcprobe/cdp.html' }); console.log('open', shown(o));
const tab = o.tab.id;
console.log('frames after open', await frames());
guard(); console.log('cdp_status', shown(await H.cdp_status({})));
guard(); console.log('console (attach)', shown(await H.console_messages({ tab_id: tab })));
guard(); console.log('trusted_click', shown(await H.trusted_click({ tab_id: tab, selector: '#go' })), await ds(tab));
guard(); const snap = await H.snapshot({ tab_id: tab, interactive_only: true }); console.log('snapshot', snap.snapshot);
guard(); console.log('trusted_type via ref', shown(await H.trusted_type({ tab_id: tab, selector: 'ref=e2', text: 'hi arc' })), await ds(tab));
guard(); console.log('console', shown(await H.console_messages({ tab_id: tab })));
guard(); const shot = await H.screenshot({ tab_id: tab });
const img = (shot.content || []).find((c) => c.type === 'image');
if (img) { writeFileSync('/private/tmp/claude-501/-Users-db-Burnes-Center-Fulltime-ME/2d0e1ee7-52d8-489a-b564-da766d0888ce/scratchpad/arcprobe/cdp-shot.png', Buffer.from(img.data, 'base64')); console.log('screenshot bytes', Buffer.from(img.data, 'base64').length); } else console.log('screenshot', shown(shot));
console.log('frames end', await frames());
guard(); console.log('close', shown(await H.close_own_tabs({})));
